export const selectDato = [
  { name: "  Elija tipo  ", value: "" },
  { name: "Archivo", value: "file" },
  { name: "Área de texto", value: "textarea" },
  { name: "Checkbox", value: "checkbox" },
  { name: "Fecha", value: "date" },
  { name: "Email", value: "email" },
  { name: "Número", value: "number" },
  { name: "Radio", value: "radio" },
  { name: "Telefono", value: "tel" },
  { name: "Texto", value: "text" },
  { name: "Sección", value: "section" },
  { name: "Select", value: "select" },
  { name: "URL", value: "url" },
];
